### ISSUE TITLE
bug: the package may have incorrect main/module/exports specified in its package.json

### ISSUE THREAD

**Issue by Arenukvern** [indentjs/objectorarray#3]
Hello.

Thank you for your plugin!

Found the following error during rollup compilation:

```bash
[commonjs] Failed to resolve entry for package "objectorarray". The package may have incorrect main/module/exports specified in its package.json.
```

In node_modules (see it picture below), package.json entry pointed to `dist/index` , however index placed in root folder, that cause an error above.

![image](https://user-images.githubusercontent.com/15068151/110778426-6149ab80-8273-11eb-8239-189a78777636.png)

**Comment by johnsusek** [comment]
I got this in a typescript project, and I had to add: 

```
  "ignore": [
    "./node_modules"
  ],
```

to my tsconfig.json

hope it helps :)

☮️

**Comment by ath0mas** [comment]
Node.js v16 deprecation for this now:
```
(node:6764) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\MyProject\node_modules\objectorarray\package.json' of 'dist/index.js'. Please either fix that or report it to the module author
```
See https://nodejs.org/api/deprecations.html#DEP0128

**Comment by deadcoder0904** [comment]
Yep, facing the same thing. Please release a new version without `main` field :)

**Comment by hanszhoou** [comment]
@Arenukvern @deadcoder0904 

Fixed by https://github.com/zhouhanseng/objectorarray/commit/d5021ac64ed9147ceaedcb97a1c8156f0143018b.

[endent@2.1.0](https://www.npmjs.com/package/endent) released.

PS. Could you please help me to close this issue, since I lost my 2 factor authentic token, this project has moved to https://github.com/zhouhanseng/objectorarray

**Comment by jayxiaolei** [comment]
I facing the same thing,
![image](https://user-images.githubusercontent.com/77085146/164366722-c760ee39-7b93-4a50-9f4e-dfcdc58b7b3d.png)
![image](https://user-images.githubusercontent.com/77085146/164366741-8387f1da-c3ef-4356-b285-2c330d5bb4eb.png)
how to resolve it ,my node version is 16.0.0

**Comment by HakobSargsyan** [comment]
> I facing the same thing, ![image](https://user-images.githubusercontent.com/77085146/164366722-c760ee39-7b93-4a50-9f4e-dfcdc58b7b3d.png) ![image](https://user-images.githubusercontent.com/77085146/164366741-8387f1da-c3ef-4356-b285-2c330d5bb4eb.png) how to resolve it ,my node version is 16.0.0

is it solved @jayxiaolei ?

**Comment by BariqDharmawan** [comment]
> > I facing the same thing, ![image](https://user-images.githubusercontent.com/77085146/164366722-c760ee39-7b93-4a50-9f4e-dfcdc58b7b3d.png) ![image](https://user-images.githubusercontent.com/77085146/164366741-8387f1da-c3ef-4356-b285-2c330d5bb4eb.png) how to resolve it ,my node version is 16.0.0
> 
> is it solved @jayxiaolei ?

Same question, is it solved? How to solve that

**Comment by leah-committed** [comment]
Same question, is it solved? How to solve that
